# Generated by Django 2.2.2 on 2019-06-21 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(default='', help_text='Ex.: Tylenol', max_length=100, verbose_name='Medicamento')),
                ('codigo_processo', models.CharField(default='', help_text='Ex.: 250000112969983', max_length=100, verbose_name='Codigo do Processo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_tarefa', models.CharField(default='', help_text='Ex.: ACME Inc', max_length=100, verbose_name='Descricao da Tarefa')),
                ('responsavel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peticionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(default='', help_text='Ex.: 0530391/19-5 (14/06/2019)', max_length=100, verbose_name='Expediente (Dt. Expediente)')),
                ('n_protocolo', models.CharField(default='', help_text='Ex.: 25352.408326/2019-31', max_length=100, verbose_name='Numero do Protocolo')),
                ('assunto', models.CharField(default='', help_text='Ex.: 10708 - RPF/Sumário - Renovação de Registro - Medicamento Novo', max_length=400, verbose_name='Assunto')),
                ('encontrase', models.CharField(default='', help_text='Ex.: GEAAR - GERÊNCIA DE ANÁLISE E AVALIAÇÃO DE RISCO', max_length=300, verbose_name='Encontra-se')),
                ('data_encontrase', models.CharField(default='', help_text='Ex.: 14/06/2019', max_length=100, verbose_name='Encontra-se desde:')),
                ('situacao', models.CharField(default='', help_text='Ex.: Distribuído para a área responsável', max_length=1000, verbose_name='Situação')),
                ('publicacao', models.CharField(default='', help_text='Ex.: Não Publicado ou 1.513 - 14/06/2018', max_length=100, verbose_name='Medicamento')),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Processo')),
            ],
        ),
    ]
